### ISSUE TITLE
add lib

### ISSUE THREAD

**Issue by dsimonet** [Guillaumebeuzeboc/mqtt_cpp#1]
sudo apt-get install libboost-all-dev
sudo apt install libmosquittopp-dev

**Comment by Guillaumebeuzeboc** [comment]
libboost not specific to mosquitto  so no need to add it to the mosquitto install (otherwise we should also add cmake, g++..)
the second one is added now https://github.com/Guillaumebeuzeboc/mqtt_cpp/pull/2
